# -*- coding: utf-8 -*-
"""covid-19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqMqARpIuzY6BTu3WMejuDQ4N65s8Bc-
"""

!pip install dash
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go

from dash import Dash, dcc, html, Input, Output

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/covid_19_clean_complete.csv")

df = df[['Date',
         'Country/Region',
         'Confirmed',
         'Deaths',
         'Recovered',
         'Active']]

df['Date'] = pd.to_datetime(df['Date'])

df.drop_duplicates(inplace=True)

df.fillna(0, inplace=True)

df['Confirmed'] = df['Confirmed'].clip(lower=0)
df['Deaths'] = df['Deaths'].clip(lower=0)
df['Recovered'] = df['Recovered'].clip(lower=0)
df['Active'] = df['Active'].clip(lower=0)

print("\nDataset Information")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDescriptive Statistics")
print(df.describe())

total_confirmed = df['Confirmed'].sum()
total_deaths = df['Deaths'].sum()
total_recovered = df['Recovered'].sum()
total_active = df['Active'].sum()

print("\nTotal Confirmed Cases :", total_confirmed)
print("Total Deaths :", total_deaths)
print("Total Recovered :", total_recovered)
print("Total Active Cases :", total_active)

daily_cases = df.groupby('Date')[[
    'Confirmed',
    'Deaths',
    'Recovered',
    'Active'
]].sum().reset_index()

plt.figure(figsize=(14,6))

plt.plot(daily_cases['Date'],
         daily_cases['Confirmed'],
         label='Confirmed')

plt.plot(daily_cases['Date'],
         daily_cases['Deaths'],
         label='Deaths')

plt.plot(daily_cases['Date'],
         daily_cases['Recovered'],
         label='Recovered')

plt.title("Global COVID-19 Trends")
plt.xlabel("Date")
plt.ylabel("Cases")
plt.legend()

plt.show()

top_countries = df.groupby('Country/Region')['Confirmed'] \
                  .max() \
                  .sort_values(ascending=False) \
                  .head(10)

plt.figure(figsize=(12,6))

top_countries.plot(kind='bar')

plt.title("Top 10 Affected Countries")
plt.xlabel("Country")
plt.ylabel("Confirmed Cases")

plt.show()

corr = df[['Confirmed',
           'Deaths',
           'Recovered',
           'Active']].corr()

plt.figure(figsize=(8,6))

sns.heatmap(corr,
            annot=True,
            cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()

fig = px.line(
    daily_cases,
    x='Date',
    y='Confirmed',
    title='Global Confirmed Cases Over Time'
)

fig.show()

top10 = df.groupby('Country/Region')['Confirmed'] \
          .max() \
          .sort_values(ascending=False) \
          .head(10) \
          .reset_index()

fig = px.bar(
    top10,
    x='Country/Region',
    y='Confirmed',
    title='Top 10 Affected Countries',
    color='Confirmed'
)

fig.show()

pie_df = pd.DataFrame({
    'Category': ['Confirmed',
                 'Deaths',
                 'Recovered',
                 'Active'],

    'Count': [total_confirmed,
              total_deaths,
              total_recovered,
              total_active]
})

fig = px.pie(
    pie_df,
    names='Category',
    values='Count',
    title='COVID-19 Case Distribution'
)

fig.show()

fig = px.scatter(
    df,
    x='Confirmed',
    y='Deaths',
    size='Recovered',
    color='Active',
    title='Confirmed vs Deaths'
)

fig.show()

app = Dash(__name__)
countries = df['Country/Region'].unique()
app.layout = html.Div([

    html.H1(
        "COVID-19 Dashboard",
        style={'textAlign': 'center'}
    ),

    html.Br(),

    html.Label("Select Country"),

    dcc.Dropdown(
        id='country-dropdown',
        options=[{'label': country, 'value': country}
                 for country in countries],
        value='India'
    ),

    html.Br(),

    # Line Chart
    dcc.Graph(id='line-chart'),

    html.Br(),

    # Bar Chart
    dcc.Graph(id='bar-chart'),

    html.Br(),

    # Scatter Plot
    dcc.Graph(id='scatter-chart')

])

@app.callback(
    [Output('line-chart', 'figure'),
     Output('bar-chart', 'figure'),
     Output('scatter-chart', 'figure')],

    [Input('country-dropdown', 'value')]
)

def update_dashboard(selected_country):

    # Filter country data
    filtered_df = df[df['Country/Region'] == selected_country]

    # Daily grouped data
    daily = filtered_df.groupby('Date')[[     'Confirmed',
     'Deaths',
     'Recovered',
     'Active'
 ]].sum().reset_index()

    # Line Chart
    line_fig = px.line(
        daily,
        x='Date',
        y=['Confirmed', 'Deaths', 'Recovered'],
        title=f'COVID-19 Trends in {selected_country}'
    )

    # Bar Chart
    bar_fig = px.bar(
        daily,
        x='Date',
        y='Confirmed',
        title=f'Confirmed Cases in {selected_country} Over Time'
    )

    # Scatter Plot
    scatter_fig = px.scatter(
        daily,
        x='Confirmed',
        y='Deaths',
        size='Recovered',
        color='Active',
        title=f'Confirmed vs. Deaths in {selected_country}'
    )

    return line_fig, bar_fig, scatter_fig

print("INSIGHTS:")

print("1. Countries with high confirmed cases have higher risk levels.")

print("2. There is a strong relationship between confirmed cases and deaths.")

print("3. Higher recovery numbers indicate improvement in healthcare systems.")

print("4. Active cases represent the current pandemic situation in each country.")

print("5. Data visualization helps understand trends and supports decision making.")